package com.mercadolibre.be_java_hisp_w31_g07.service;

import com.mercadolibre.be_java_hisp_w31_g07.dto.response.FollowersPostsResponseDto;
import com.mercadolibre.be_java_hisp_w31_g07.dto.response.PostResponseDto;

import java.util.List;
import java.util.UUID;

import com.mercadolibre.be_java_hisp_w31_g07.dto.request.PostDto;
import com.mercadolibre.be_java_hisp_w31_g07.dto.response.SellerPromoPostsCountResponseDto;
import com.mercadolibre.be_java_hisp_w31_g07.exception.BadRequest;


public interface IPostService {
    /**
     * Allows a seller to create a new post.
     *
     * @param newPost {@link PostDto} contains all data to create a Post, except
     *                its UUID, which is generated by this service
     * @return created post converted to {@link PostResponseDto}
     * @throws BadRequest if the seller trying to create the post
     * does not exist
     */
    public PostResponseDto createPost(PostDto newPost);

    /**
     * Returns the most recent posts from sellers followed by the given buyer.
     * Only includes posts from the last two weeks, sorted by newest first.
     *
     * @param buyerId the unique identifier of the buyer.
     *
     */
    public FollowersPostsResponseDto getLatestPostsFromSellers(UUID buyerId);

    public SellerPromoPostsCountResponseDto getPromoPostsCount(UUID sellerId);

    // ------------------------------ START TESTING ------------------------------
    // FOR TESTING PURPOSES ONLY
    // This endpoint is not part of the original requirements
    // and is only used to verify the functionality of the followSeller method.

    // It should be removed in the final version of the code.

    public PostResponseDto findPost(UUID postId);
    // ------------------------------ END TESTING ------------------------------
}
