package com.mercadolibre.be_java_hisp_w31_g07.service;

import com.mercadolibre.be_java_hisp_w31_g07.dto.request.PostDto;
import com.mercadolibre.be_java_hisp_w31_g07.dto.response.PostResponseDto;
import com.mercadolibre.be_java_hisp_w31_g07.exception.NotFoundException;

import java.util.UUID;

public interface IPostService {
    /**
     * Allows a seller to create a new post.
     *
     * @param newPost {@link PostDto} contains all data to create a Post, except
     *                its UUID, which is generated by this service
     * @return created post converted to {@link PostResponseDto}
     * @throws NotFoundException if the seller trying to create the post
     * does not exist
     */
    public PostResponseDto createPost(PostDto newPost);

    // ------------------------------ START TESTING ------------------------------

    // FOR TESTING PURPOSES ONLY
    // This endpoint is not part of the original requirements
    // and is only used to verify the functionality of the followSeller method.
    // It should be removed in the final version of the code.

    public PostResponseDto findPost(UUID postId);

    // ------------------------------ END TESTING ------------------------------
}
